# Generated by Django 2.2.6 on 2019-12-05 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='type',
            new_name='userType',
        ),
    ]
