# Generated by Django 2.2.6 on 2019-12-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20191205_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='currentUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(blank=True, max_length=100)),
                ('userType', models.IntegerField(blank=True)),
            ],
        ),
    ]
