# Generated by Django 2.2.6 on 2019-10-25 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PB_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=100)),
                ('priority', models.IntegerField()),
                ('story_point', models.IntegerField(default=1)),
            ],
        ),
    ]
