# Generated by Django 2.2.6 on 2019-10-25 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PBI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pb_item',
            old_name='Status',
            new_name='status',
        ),
    ]
