# Generated by Django 2.2.6 on 2019-10-25 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PBI', '0002_auto_20191025_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pb_item',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
