# Generated by Django 2.2.6 on 2019-10-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PBI', '0004_auto_20191025_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='PB_edit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=100)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('priority', models.IntegerField()),
                ('story_point', models.IntegerField()),
            ],
        ),
    ]
