# Generated by Django 2.2.6 on 2019-10-25 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PBI', '0005_pb_edit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PB_edit',
        ),
    ]
