# Generated by Django 2.2.5 on 2019-11-08 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PBI', '0006_delete_pb_edit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprint_no', models.IntegerField(default=1)),
                ('sprint_end_time', models.DateTimeField(default='', max_length=400)),
                ('sprint_Duration', models.IntegerField(default=1)),
            ],
        ),
        migrations.RenameField(
            model_name='pb_item',
            old_name='feature',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='pb_item',
            old_name='priority',
            new_name='priority_no',
        ),
        migrations.AddField(
            model_name='pb_item',
            name='confirmation',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='pb_item',
            name='user_story',
            field=models.CharField(default='', max_length=400),
        ),
    ]
