# Generated by Django 2.2.6 on 2019-11-07 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PBI', '0006_delete_pb_edit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pb_item',
            options={'ordering': ['priority']},
        ),
    ]
