# Generated by Django 2.2.5 on 2019-11-09 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PBI', '0007_auto_20191108_0657'),
        ('PBI', '0007_auto_20191107_0305'),
    ]

    operations = [
    ]
