# Generated by Django 2.2.5 on 2019-11-09 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PBI', '0008_merge_20191109_0306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pb_item',
            options={'ordering': ['priority_no']},
        ),
        migrations.AlterField(
            model_name='pb_item',
            name='status',
            field=models.CharField(blank=True, default='Pending', max_length=100),
        ),
    ]
