# Generated by Django 2.2.6 on 2019-11-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PBI', '0009_auto_20191109_0506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprint_no', models.IntegerField()),
                ('capacity', models.IntegerField()),
            ],
        ),
    ]
