# Generated by Django 2.2.6 on 2019-11-11 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PBI', '0010_sprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('ended', 'Ended')], default='active', max_length=100),
        ),
        migrations.AlterField(
            model_name='pb_item',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Finished', 'Finished'), ('Unfinished', 'Unfinished')], default='Pending', max_length=100),
        ),
    ]
