# Generated by Django 2.2.6 on 2019-11-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PBI', '0012_pb_item_sprint_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pb_item',
            name='priority_no',
            field=models.IntegerField(unique=True),
        ),
    ]
