# Generated by Django 2.2.6 on 2019-11-07 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sprint_backlog_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PBI', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('status', models.CharField(blank=True, default='pending', max_length=100)),
                ('owner', models.CharField(max_length=100)),
                ('estimation', models.IntegerField()),
            ],
            options={
                'ordering': ['estimation'],
            },
        ),
    ]
