# Generated by Django 2.2.6 on 2019-11-07 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprint_backlog', '0003_auto_20191107_0835'),
    ]

    operations = [
        migrations.DeleteModel(
            name='capacity',
        ),
    ]
