# Generated by Django 2.2.6 on 2019-11-10 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprint_backlog', '0005_capacity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sprint_backlog_item',
            options={'ordering': ['PBI', '-status', 'estimation']},
        ),
    ]
